apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: my_app
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/service.yaml
