apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-recommendation
  labels:
    app : my-k8s-music-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-recommendation
  template:
    metadata:
      labels:
        app: music-recommendation
    spec:
      containers:
        - name: music-recommendation
          image: diocsin/my_app:latest
          ports:
            - containerPort: 80