name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t $DOCKER_USERNAME/my_app:latest .
          docker push $DOCKER_USERNAME/my_app:latest

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      - name: Start Minikube
        run: minikube start --driver=virtualbox

      - name: Set up Kubernetes context
        run: minikube kubectl config use-context minikube

      - name: Deploy to Minikube
        run: kubectl apply -f k8s/deployment.yaml

      - name: Wait for deployment to be ready
        run: kubectl rollout status deployment/my_app

      - name: Expose service
        run: kubectl expose deployment my_app --type=NodePort --port=80

      - name: Get Minikube IP
        run: minikube ip

      - name: Display service URL
        run: echo "Service URL: http://$(minikube ip):$(kubectl get service my_app -o jsonpath='{.spec.ports[0].nodePort}')"
